server:
  port: 8080
  context-path: /
spring:
  application:
    name: aaaspringcloudtest
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: HTML5
  devtools:
    restart:
      enabled: true
      additional-paths:
        - src/main/java
  profiles:
    active: local

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.jason.trade.model

logging:
  level:
     com.jason.trade.mapper : debug

#security:
#  user:
#    name: iotuser           # 配置登录的账号是user
#    password: CF7hqp*Y       # 配置登录的密码是iot123
#  basic:
#    enabled: false
#
#cluster:
#  eureka:
#    ip1: 172.16.1.33 #223.105.5.102
#    ip2: 172.16.1.34 #223.105.5.104
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://${security.user.name}:${security.user.password}@${cluster.eureka.ip1}:11000/eureka/,http://${security.user.name}:${security.user.password}@${cluster.eureka.ip2}:11000/eureka/
#  instance:
#    preferIpAddress: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#
#feign:
#  hystrix:
#    enabled: true